version: '2.1'
services:
    hermeneut-app:
        image: hermeneut
        mem_limit: 1024m
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://hermeneut-postgresql:5432/hermeneut
            - JHIPSTER_SLEEP=30
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=hermeneut-elasticsearch:9300
            - JHIPSTER_REGISTRY_PASSWORD=53bqDrurQAthqrXG
            - HERMENEUT_VERSION
            - EMAIL_HOST
            - EMAIL_PORT
            - EMAIL_USERNAME
            - EMAIL_ADDRESS
            - EMAIL_PASSWORD
            - EMAIL_PROTOCOL
            - EMAIL_TLS
            - EMAIL_AUTH
            - SERVER_URL
        ports:
            - 8080:8080
        networks:
          - backend
        depends_on:
          jhipster-registry:
            condition: service_healthy
          hermeneut-postgresql:
            condition: service_started
          hermeneut-elasticsearch:
            condition: service_started
    hermeneut-postgresql:
        image: postgres:9.6.5
        mem_limit: 256m
        environment:
            - POSTGRES_USER=hermeneut
            - POSTGRES_PASSWORD=tuenemreh
        networks:
          - backend
    hermeneut-elasticsearch:
        image: elasticsearch:2.4.6
        mem_limit: 512m
        networks:
          - backend
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        mem_limit: 512m
        ports:
            - 8761:8761
        networks:
          - backend
        volumes:
          - ${PWD}/Ping.jar:/Ping.jar
        healthcheck:
          test: ["CMD", "java", "-jar", "/Ping.jar", "localhost", "8761"]
          interval: 30s
          retries: 20
networks:
  backend:
    driver: "bridge"