version: '2'
services:
    hermeneut-app:
        image: hermeneut
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://hermeneut-postgresql:5432/hermeneut
            - JHIPSTER_SLEEP=30
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=hermeneut-elasticsearch:9300
            - JHIPSTER_REGISTRY_PASSWORD=53bqDrurQAthqrXG
        ports:
            - 8080:8080
    hermeneut-postgresql:
        image: postgres:9.6.5
        environment:
            - POSTGRES_USER=hermeneut
            - POSTGRES_PASSWORD=tuenemreh
    hermeneut-elasticsearch:
        image: elasticsearch:2.4.6
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
