version: '2.1'
services:
    hermeneut-app:
        image: dev-hermeneut.eng.it/hermeneut:${HERMENEUT_VERSION:-latest}
        mem_limit: 1024m
        environment:
            - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod,swagger}
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://hermeneut-postgresql:5432/hermeneut
            - JHIPSTER_SLEEP=30
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=hermeneut-elasticsearch:9300
            - JHIPSTER_REGISTRY_PASSWORD=53bqDrurQAthqrXG
            - HERMENEUT_VERSION
            - HERMENEUT_LOG_DIR=${HERMENEUT_LOG_DIR:-${PWD}}
            - HERMENEUT_LOG_LEVEL=${HERMENEUT_LOG_LEVEL:-debug}
            - HERMENEUT_LOG_MAX_HISTORY_HOURS=${HERMENEUT_LOG_MAX_HISTORY_HOURS:-168}
            - HERMENEUT_LOG_MAX_FILE_SIZE=${HERMENEUT_LOG_MAX_FILE_SIZE:-5MB}
            - HERMENEUT_LOG_MAX_CAPACITY=${HERMENEUT_LOG_MAX_CAPACITY:-3GB}
            - EMAIL_HOST
            - EMAIL_PORT
            - EMAIL_USERNAME
            - EMAIL_ADDRESS
            - EMAIL_PASSWORD
            - EMAIL_PROTOCOL
            - EMAIL_TLS
            - EMAIL_AUTH
            - SERVER_URL
            - KAFKA_GROUP_ID=${KAFKA_GROUP_ID:-hermeneut-consumer}
            - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-localhost:9092}
            - KAFKA_RISK_PROFILE_TOPIC=${KAFKA_RISK_PROFILE_TOPIC:-risk-profile-topic}
        ports:
            - 8080:8080
        volumes:
          - ${HERMENEUT_LOG_DIR}:/logs
        networks:
          - backend
        depends_on:
          jhipster-registry:
            condition: service_healthy
          hermeneut-postgresql:
            condition: service_started
          hermeneut-elasticsearch:
            condition: service_started
    hermeneut-postgresql:
        image: postgres:9.6.5
        mem_limit: 256m
        environment:
            - POSTGRES_USER=hermeneut
            - POSTGRES_PASSWORD=tuenemreh
        networks:
          - backend
    hermeneut-elasticsearch:
        image: elasticsearch:2.4.6
        mem_limit: 512m
        networks:
          - backend
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        mem_limit: 512m
        ports:
            - 8761:8761
        networks:
          - backend
        volumes:
          - ${PWD}/Ping.jar:/Ping.jar
        healthcheck:
          test: ["CMD", "java", "-jar", "/Ping.jar", "localhost", "8761"]
          interval: 30s
          retries: 20
networks:
  backend:
    driver: "bridge"